### ISSUE TITLE
WIP Ungenutzte Accordions in der Prozessansicht disablen / re-enablen falls diese benötigt werden

### ISSUE THREAD

**Issue by twonkos** [Praxisprojekt2021/praxisprojekt#103]
## Bereich 

* Frontend

## Beschreibung

Wie im Titel beschrieben, Accordions die nicht benötigt werden sind aufklappbar mit leeren Einträgen.

Macht es an dieser Stelle eurer Meinung nach Sinn, diese zu disablen wie im Component View? Oder sollten diese einsehbar bleiben damit der Nutzer sich einen "Überblick" vll. verschaffen kann?

## Lösungsvorschläge

Ähnliche Vorgehensweise wie im Component View

## Testen 

Ungenutzte Accordions nicht aufklappbar wenn diese nicht benötigt werden. Wird eine Komponente hinzugefügt welche den Feature XY Accordion benötigt -> Wieder aufklappbar

## Verantwortlicher als funktionaler Reviewer
- [ ] tba 

### Anmerkungen

Würde erledigt werden im 246 branch

**Comment by tomhinzmann** [comment]
@twonkos @NimsaJ150 , @Timo-Buecher  und ich finden, sie sollten aufklappbar bleiben, damit man jederzeit die Möglichkeit hat, Target Metrics eingeben zu können. Das ist dann auch konform mit den Fachgilden Interviews, bei denen ein Learning war, dass die Komponenten eher vom technischen Experten und die Prozesse eher vom fachlichen Experten eingetragen werden - wir sollen also die Möglichkeit bieten, dass beide Parteien unabhängig voneinander arbeiten können.

Insofern besteht der Bedarf nicht und das Issue wird geschlossen.
