### ISSUE TITLE
131: Überprüfen der Prozessmetriken nicht in korrekte Richtung

### ISSUE THREAD

**Issue by prinzpaul** [Praxisprojekt2021/praxisprojekt#106]
## Bereich 
* Frontend
* Backend
   - Logik

(vermutlich Logik, ggf. Frontend)

## Beschreibung
Metriken werden nicht gemäß Framework Logik überprüft, sondern "größer ist immer besser"
<img width="1412" alt="Bildschirmfoto 2021-04-22 um 14 06 03" src="https://user-images.githubusercontent.com/43496690/115711560-f57b5800-a373-11eb-823a-f80c78ff93dc.png">
(Metriken 1-4, 6, 7 sollten rot sein)

## Verantwortlicher als funktionaler Reviewer
Paul

**Comment by NimsaJ150** [comment]
![image](https://user-images.githubusercontent.com/44087726/115712310-e943ca80-a374-11eb-8419-16effedddcb0.png)

Processing bekommt aktuell diese Daten zu den Metriken, dh aktuell ist jede MEtrik grün bei der actual > target. Zu prüfen, ob die cypher query irgendetwas falsch ausliest (es waren schon mal die Richtigen Daten vorhanden) oder die Daten in der Datenbank geändert wurden. @jonathan112358 @Timo-Buecher

**Comment by Sofie273** [comment]
Teilweise waren die falschen fulfill Bedingungen in der mapping_metrics_definition hinterlegt. Wurde korrigiert. Teste jetzt noch, ob an anderer Stelle ein Fehler auftritt. Metriken wurden in der Datenbank neu angelegt
