### ISSUE TITLE
Dauerladescreen bei falschen uids in der URL (Ungleich Issue #95)

### ISSUE THREAD

**Issue by tomhinzmann** [Praxisprojekt2021/praxisprojekt#107]
## Bereich 

* Frontend

## Beschreibung
Wenn die eingegebene Process- oder Component-UID falsch ist, bzw. zu dieser UID keine zugehörige Node existiert, gibt es einen Dauerladescreen. Betrifft also beide Ansichten. Bitte beheben!

## Verantwortlicher als funktionaler Reviewer
- [ ] @tomhinzmann

**Comment by Sofie273** [comment]
Ich habe mal reingeschaut. Der Fehler kommt, da wir den 500 Error*, der vom Backend kommt im Frontend nicht abfangen.

*
list index out of range
{"success": false, "error_type": "IndexError", "error_message": "list index out of range"}

Ich habe für die Component View das Ganze gefixxt, aus irgendeinem Grund kommt bei der Process View das Alert allerdings dreimal und erst dann wird der Loading Screen geschlossen. Hier Hilfe erbeten. Siehe Branch I95_Dauerladescreen_bei_falschen_UIDs
