### ISSUE TITLE
Auslagern von Tabellenheader Helper Texten

### ISSUE THREAD

**Issue by tomhinzmann** [Praxisprojekt2021/praxisprojekt#109]
## Bereich 

* Frontend

## Beschreibung
Tabellen Header Helper Texte auf der Prozess Ansicht stehen derzeit statisch im Code und sollten in ein entsprechendes (vermutlich neues) json file ausgelagert werden.

## Verantwortlicher als funktionaler Reviewer
- [ ] @tomhinzmann

**Comment by tomhinzmann** [comment]
@N3R1K 
1.) Bitte auf einem neuen Branch umsetzen, sobald der 287 gemerged wurde, das dürfte vielleicht schon morgen der Fall sein.
2.) Es geht nicht um diese helper oder example Texte, es geht um die Tabellen Header Texte, also die Erklärungen zu Sum, Average, Std. Dev. etc., verstehst du? Die stehen aktuell noch hart im Code. Die Texte, die du meinst, sind dort in der mapping_metrics_definition.json gut aufgehoben.

**Comment by N3R1K** [comment]
@tomhinzmann
Ah ok, thx, ja habe es verstanden, also hier dann das ab Zeile 202.
https://github.com/Praxisprojekt2021/praxisprojekt/blob/287_infotexte_metriken/frontend/static/js/process-editor.js

**Comment by tomhinzmann** [comment]
> @tomhinzmann
> Ah ok, thx, ja habe es verstanden, also hier dann das ab Zeile 202.
> https://github.com/Praxisprojekt2021/praxisprojekt/blob/287_infotexte_metriken/frontend/static/js/process-editor.js

Exakt! Es geht um die Title Tags der Table Headers.

**Comment by tomhinzmann** [comment]
@N3R1K Der 287 ist auf dem Master, du kannst loslegen!
