### ISSUE TITLE
JS Code Cleanup u.a. process-editor.js

### ISSUE THREAD

**Issue by tomhinzmann** [Praxisprojekt2021/praxisprojekt#114]
## Bereich 

* Frontend

## Beschreibung

Die Funktion von fillMetricRows im process-editor.js file enthält im weiteren Sinne redundaten Code. Die Funktion ist dazu da, eine einzelne Tabellenzeile als HTML Element zu liefern. Abhängig davon, ob tatsächlich actual und/oder target Werte eingetragen sind, werden die Felder unterschiedlich gefüllt. Andere Felder (etwa Metrikname, Helper Icon etc.) sind aber gleich und sollten nicht redundant im Code stehen, sondern nur einmal gesetzt werden (Fehleranfälligkeit, etwa wenn der Helpertext anders zusammengesetzt werden soll etc.).

Die Funktion bitte überarbeiten, sodass keine Redundanzen bestehen bleiben. Bei Fragen bitte an die funktionalen Reviewer wenden!

Zudem zu bearbeiten sind:
- Modularisierung/ Gleichziehen CreateEditComponent, CreateEditProcess -> Bezug auf Eventlistener: in helper.js auslagern
- Modularisieren createMetricsSection

## Testen 

Die erfolgreiche Adressierung der Issues werden vom funktionalen Reviewer entsprechend anhand des Codes oder durch Frontend-Test abgenommen.

## Verantwortlicher als funktionaler Reviewer
- [ ] @NimsaJ150

**Comment by NimsaJ150** [comment]
@twonkos @Sofie273 Macht dazu bitte gerne vorher einen Termin aus, um das kurz abzusprechen :)
