### ISSUE TITLE
WIP: 111: Keine Infotexte bei den Metriken

### ISSUE THREAD

**Issue by ArtemFey** [Praxisprojekt2021/praxisprojekt#115]
## Bereich

* Frontend
  - Einzelkomponenten Ansicht

## Beschreibung
In der Einzelkomponenten Ansicht sollen Infotexte, wenn man über das (i) mit der Maus fährt, neben den Metriken erscheinen.
Die Infotexte erscheinen weder durch das darüberfahren noch durch das anklicken des (i) Symbols

## Testen 
Durch das anklicken des (i) Symbols

## Verantwortlicher als funktionaler Reviewer
- [ Artem, Sebastian]

**Comment by NimsaJ150** [comment]
@ArtemFey 
![image](https://user-images.githubusercontent.com/44087726/115957667-12469580-a504-11eb-8d12-df3ccec86e69.png)
Funktioniert bei mir, gerne nochmal prüfen oder genauer beschreiben, wo ein Fehler auftritt
