### ISSUE TITLE
WIP: 109 & 110: Sehr lange Ladezeit - vielleicht auch unendlich bis man die Aktion abbricht

### ISSUE THREAD

**Issue by ArtemFey** [Praxisprojekt2021/praxisprojekt#116]
## Bereich 

* Frontend
* Backend
   - REST-API
   - Logik
   - Database-Handler
* Database

## Beschreibung
In beiden Testfällen sollen bei der Erstellung einer Komponente, entweder die Metriken oder die Kategorie freigelassen werden, dabei soll eine Fehlermeldung erscheinen. Die Fehlermeldung erscheint auch, jedoch versetzt es die Ansicht in den Lademodus, aus welchen man nur herauskommt, wenn man auf den zurück Pfeil im Browser klickt.

## Verantwortlicher als funktionaler Reviewer
Artem und Sebastian

**Comment by NimsaJ150** [comment]
@ArtemFey Redundant zu #95 ?
