### ISSUE TITLE
Test Case 112: Komponente wird ohne Namen erstellt

### ISSUE THREAD

**Issue by ArtemFey** [Praxisprojekt2021/praxisprojekt#117]
## Bereich 

* Frontend
* Backend
   - REST-API
   - Logik
   - Database-Handler
* Database

## Beschreibung
Es sollte eine Komponente erstellt werden, bei dieser sollte jedoch das Feld für den Namen freigelassen werden, dabei wird erwartet, dass eine Fehlermeldung auftritt. Es tritt keine Fehlermeldung auf und die Komponente wird ohne Namen erstellt.

## Verantwortlicher als funktionaler Reviewer
Sebastian und Artem

**Comment by NimsaJ150** [comment]
Ist in #67 schon enthalten
