### ISSUE TITLE
114: In der Komponentenansicht ist der Home-button nicht vorhanden

### ISSUE THREAD

**Issue by ArtemFey** [Praxisprojekt2021/praxisprojekt#118]
## Bereich 

* Frontend

## Beschreibung
Man sollte aus der Komponentenansicht mit dem links-oben sich befindlichen Home-Button auf die Startseite zurück geführt werden. Der Home-Button ist nicht vorhanden

## Lösungsvorschläge

Einbindung des traslater.js fehlt im component.html

## Verantwortlicher als funktionaler Reviewer
Sebastian und Artem

**Comment by NimsaJ150** [comment]
Umsetzung in #67
