### ISSUE TITLE
[Test Case 122]: Prozessansicht keine Information im Infosymbol wird nicht angezeigt

### ISSUE THREAD

**Issue by ArtemFey** [Praxisprojekt2021/praxisprojekt#119]
## Bereich 

* Frontend
* Backend
   - REST-API
   - Logik
   - Database-Handler
* Database

## Beschreibung
Es soll geprüft werden, ob hinter den Info Symbolen in der Prozessansicht bei den jeweiligen Features, die Beschreibung angezeigt wird. Die Infosymbole haben momentan keine Funktion und somit wird die Beschreibung auch nicht angezeigt
## Verantwortlicher als funktionaler Reviewer
- Sebastian & Artem

### Anmerkungen
< Das gleiche bei der Komponentenansicht>

**Comment by NimsaJ150** [comment]
@ArtemFey 

![image](https://user-images.githubusercontent.com/44087726/115958189-a9ace800-a506-11eb-99a9-cc1a00b4c446.png)

Bitte nochmal prüfen und sonst den Fehler spezifizieren

**Comment by ArtemFey** [comment]
@NimsaJ150 Cache geleert, aktualisiert usw. leider funktioniert es immer noch nicht. Die Info wird nicht angezeigt.
Das ist unser link zur der hoffentlich aktuellen version: https://praxisprojekt-2021.ew.r.appspot.com/
