### ISSUE TITLE
[Test Case 131]: Bei den Featerus hat der Wert für Std. zuviele nachkommastellen

### ISSUE THREAD

**Issue by ArtemFey** [Praxisprojekt2021/praxisprojekt#120]
## Bereich 

* Frontend
* Backend
   - REST-API
   - Logik
   - Database-Handler
* Database

## Beschreibung
Die Zahlen sollen auf die Korrektheit und Länge der Nachkommastellen (max 4) überprüft werden. Die Zahlen sind korrekt, jedoch hat Std. deutlich mehr Nachkommastellen als 4

## Verantwortlicher als funktionaler Reviewer
Artem und Sebastian

**Comment by NimsaJ150** [comment]
In #66 enthalten?
