### ISSUE TITLE
null als Prozessrisiko Wert von Startseite entfernen

### ISSUE THREAD

**Issue by NimsaJ150** [Praxisprojekt2021/praxisprojekt#131]
## Bereich 

* Frontend

## Beschreibung

Auf der Startseite wird immer noch das technische null angezeigt, genauso auf der Prozessview NaN

## Verantwortlicher als funktionaler Reviewer
- [ ] @NimsaJ150

**Comment by N3R1K** [comment]
@NimsaJ150 Hi, soll es stattdessen "0" sein, oder eine andere Bezeichnung haben?
