### ISSUE TITLE
Frontend String Formatierung nachziehen

### ISSUE THREAD

**Issue by tomhinzmann** [Praxisprojekt2021/praxisprojekt#134]
## Bereich 

* Frontend

## Beschreibung

Im Frontend bitte auch entweder alle zusammengesetzten Stings mit \`Text \` + Variable oder mit "Text ${Variable}" vereinheitlichen, also entweder oder. Bitte abstimmen mit funktionalem Reviewer!

## Verantwortlicher als funktionaler Reviewer
- [ ] @jonathan112358 
- [ ] @NimsaJ150

**Comment by AngelinaSp** [comment]
@NimsaJ150 @jonathan112358 wann hättet ihr kurz zeit um darüber zu sprechen wie es vereinheitlicht werden soll?

**Comment by NimsaJ150** [comment]
@AngelinaSp theoretisch jetzt kurz?
