### ISSUE TITLE
WIP: Überarbeiten der Ampelfunktionen

### ISSUE THREAD

**Issue by Sofie273** [Praxisprojekt2021/praxisprojekt#137]
## Bereich
* Frontend

## Beschreibung
Leftover TO DO: die Ampel zur Indikation des Risikos sollte auf verschiedene Requirements reagieren können 
Anpassungen in getcirclecolor und renderstatuscolumn notwendig

## Verantwortlicher als funktionaler Reviewer
- [ ] @tomhinzmann  

## Anmerkungen
Evtl out of scope?

**Comment by Timo-Buecher** [comment]
@tomhinzmann @NimsaJ150 das ist nicht mehr aktuell oder? Wenn ja pls closen

**Comment by NimsaJ150** [comment]
@Timo-Buecher ist die Skala, ab wann es gelb wird, denn mit der fachlichen Seite abgesprochen worden? @JLFrick
Ich hatte im Kopf, dass bei der Umsetzung einfach ein Wert angenommen wurde

**Comment by lucabloe** [comment]
@NimsaJ150
Jan-Luca hat mir gesagt, dass die Anforderung so in der Doku steht:
<80%         --> rot
80% - 90% --> gelb
>90%         --> grün

So ist es im Code ja auch umgesetzt, also kann meiner Meinung nach das Issue geschlossen werden.
