### ISSUE TITLE
Update outdatedThreshold

### ISSUE THREAD

**Issue by Sofie273** [Praxisprojekt2021/praxisprojekt#139]
## Bereich 
* Frontend

## Beschreibung
Leftover TO DO: 
Threshold im Code ändern

## Verantwortlicher als funktionaler Reviewer
- [ ] @tomhinzmann 

### Anmerkungen
-> Absprache fachliche Gilde, auch bzgl Vorstellung
-> Zeit anpassen
-> Zu bearbeiten in modals.js file

**Comment by jonathan112358** [comment]
Warum sollte das out of scope sein, ich verstehe das als kleine Anpassung bevor wir es abgeben

**Comment by Sofie273** [comment]
das ändern im Code ist ein final task definitiv, man kann die notiz aber auch so verstehen, dass das durch den nutzer erfolgen soll und dann wäre es mmn out of scope. Aber rein die Änderung als final task natürlich nciht

**Comment by Antonio1730** [comment]
Mit Jan-Luca von Fachseite besprochen. Neuer Threshold: 1Monat.
