### ISSUE TITLE
Fehlerhafte Angabe von Summe, Min, Max bei binären Metriken

### ISSUE THREAD

**Issue by JLFrick** [Praxisprojekt2021/praxisprojekt#147]
## Bereich 

* Frontend

## Beschreibung

![image](https://user-images.githubusercontent.com/43888040/116549738-2587a580-a8f6-11eb-94d3-92e05ae97e7d.png)
![image](https://user-images.githubusercontent.com/43888040/116549747-29b3c300-a8f6-11eb-89ab-4bb7d4178bad.png)

In der Komponentenansicht sollen binäre Metriken durch ein Dropdown mit "yes" oder "No" repräsentiert werden statt durch ein Input-Feld.
In der Prozessansicht soll für diese Metriken die target-min und target-max Inputfelder ausgegraut werden.

## Lösungsvorschläge

Für die Komponentenansicht:
- Hinzufügen eines Feldes in mapping_metrics_definitions.json, welches als bool enthält, ob eine Metrik binär ist oder nicht (-> Absprache fachliche Gilde)
- bei createMetricsSection -> Prüfen, ob binary true oder false
  - bei false wie bisher das Inputfeld erstellen
  - bei true Anlegen eines select dropdowns mit drei Optionen: 
    - values: "", 0, 1 
    - Text: "", "Yes", "No"
    - auf name oder id des Feldes achten, sodass dieses später beim Speichern mit ausgelesen wird
- Überprüfen der Speicherlogik, ob Komponente noch korrekt gespeichert wird

Für Prozessansicht:
- in fillMetricRows: (fillMetricTarget?)
  - wenn Metrik binary false -> wie bisher
  - wenn Metrik binary true
    - disablen der target-min und target-max Felder bei Erstellung
    - wichtig: die Felder dürfen keine min und max Werte erhalten
- Überprüfen der Speicherlogik, ob Prozess noch korrekt gespeichert wird

## Verantwortlicher als funktionaler Reviewer
- [ ] @JLFrick

**Comment by NimsaJ150** [comment]
@JLFrick Die Funktion war bisher noch nicht umgesetzt. Wie wichtig ist das Ganze? Theoretisch würde thematisch dazu auch noch solche Dinge passen wie: bei binären Werten darf nur 0 und 1, nichts dazwischen angegeben werden. Das ist bisher auch noch nicht umgesetzt.

**Comment by JLFrick** [comment]
@NimsaJ150 meiner Meinung nach wäre die Funktion schon sehr wichtig. In Anbetracht der Seite müsst ihr jedoch wissen, ob es noch umgesetzt wird.

Bei den binären Werten muss jedoch darauf geachtet werden, dass auf Komponentenebene nur die Eingabe von 0 oder 1 (False oder True) erfolgt. Auf Prozessebene sollen Eingaben im Bereich 0 bis 1 (bzw. 0%-100%) möglich sein. Hintergrund ist, dass dort angegeben wird wie viele Komponenten diese Metrik erfüllen sollen.

**Comment by NimsaJ150** [comment]
@Timo-Buecher @JLFrick Lasst uns dazu gerne nochmal eine Termin ausmachen
