### ISSUE TITLE
Prozess-Seite wird nicht aktualisiert wenn Komponente aus Prozess gelöscht wird

### ISSUE THREAD

**Issue by JLFrick** [Praxisprojekt2021/praxisprojekt#148]
## Bereich 

* Frontend

## Beschreibung

![image](https://user-images.githubusercontent.com/43888040/116550568-3c7ac780-a8f7-11eb-9a1e-52f8b98f467d.png)

Prozess-Seite wird nicht aktualisiert wenn Komponente aus Prozess gelöscht wird. Es kommt kein Loading Screen und die Komponente wird nicht gelöscht

## Verantwortlicher als funktionaler Reviewer
- [ ] @JLFrick

**Comment by NimsaJ150** [comment]
@twonkos liegt das daran, dass durch das Design ein Element über dem Button liegt und daher dieser nicht mehr geklickt werden kann?
