### ISSUE TITLE
WIP: Loading Screen Startseite

### ISSUE THREAD

**Issue by NimsaJ150** [Praxisprojekt2021/praxisprojekt#163]
## Bereich 

* Frontend

## Beschreibung

![image](https://user-images.githubusercontent.com/44087726/116817626-9da8d200-ab67-11eb-9842-50d89041e511.png)
Auf der Startseite wird aktuell weder die innere Animation, noch der Text angezeigt

## Verantwortlicher als funktionaler Reviewer
- [ ] @tomhinzmann

**Comment by NimsaJ150** [comment]
@Sofie273 Hast du Zeit/Lust, hier nochmal nachzuschauen?

**Comment by Sofie273** [comment]
Kann den Fehler wedre local noch im Cloud Build nachvollziehen (Windows/ Chrome), Evtl ein gerätespezifisches Problem?

**Comment by Eren04** [comment]
Der Fehler wurde behoben, es lag hauptsächlich daran, dass die asynchrone Funktion getProcessList nicht asynchrone ausgeführt wurde, weil der Parameter für asyn auf false stand. Lösung in 382_Loading_Screen_Startseite, PR schon erstellt.
