### ISSUE TITLE
Erklärungstexte abgeschnitten

### ISSUE THREAD

**Issue by NimsaJ150** [Praxisprojekt2021/praxisprojekt#170]
## Bereich 

* Frontend

## Beschreibung
Erklärungstexte sind teilweise abgeschnitten. Bisher nur auf Komponentenseite gefunden.
![Bildschirmfoto 2021-05-03 um 17 20 54](https://user-images.githubusercontent.com/43496690/116904484-08c4d800-ac3e-11eb-9ef8-0a82cd88931f.png)

## Verantwortlicher als funktionaler Reviewer
- [x] @prinzpaul

**Comment by Eren04** [comment]
Problem in Branch 391 gelöst. Problem wurde durch hidden overflow im CSS verursacht. 
Infotexte wurden etwas mit Umbrüchen angepasst, damit sie besser angezeigt werden und Rechtschreibprüfung gab's gratis dazu ;)

**Comment by prinzpaul** [comment]
Ich hoffe es wird demnächst keine Gehaltserhöhung gefordert ;)

**Comment by Eren04** [comment]
Muss ich mal mit der Gewerkschaft sprechen 🗡️

**Comment by NimsaJ150** [comment]
Bitte nicht die Issues händisch schließen :) Die werden automatisch geschlossen, wenn die PRs gemergt sind :)
