### ISSUE TITLE
WIP: Anzeigefehler, abgeschnittene Zeilen

### ISSUE THREAD

**Issue by niklasschueler** [Praxisprojekt2021/praxisprojekt#173]
## Bereich 

* Frontend

## Beschreibung
Anzeigefehler, Prozess (https://praxisprojekt-2021.ew.r.appspot.com/process?uid=779714592f2045d283e9341f2a457302) wurde in google Chrome (im privaten Modul) geöffnet, dabei sind von den Metriken die Zeilen abgeschnitten 
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/44088731/117042425-4132e780-ad0c-11eb-9ec7-fd78d9e7fdd4.png">

## Reproduktion
https://praxisprojekt-2021.ew.r.appspot.com/process?uid=779714592f2045d283e9341f2a457302

## Testen 
Erneut in Google Chrome aufrufen

## Verantwortlicher als funktionaler Reviewer
- [ ] tba

**Comment by NimsaJ150** [comment]
@twonkos fällt das unter deine Skalierungstasks und ist damit behoben?

**Comment by twonkos** [comment]
> @twonkos fällt das unter deine Skalierungstasks und ist damit behoben?

Yes
