### ISSUE TITLE
WIP:Enless loading screen if wrong process id is beign given into URL

### ISSUE THREAD

**Issue by CorvinFassbender** [Praxisprojekt2021/praxisprojekt#178]
## Bereich 

* Frontend

## Beschreibung
Wenn man für die Process UID über die URL eine ungültige ID angibt kommt ein endloser Ladescreen.
![image](https://user-images.githubusercontent.com/81093076/117175105-c252b300-adce-11eb-95bb-ce42dd59cce6.png)

## Lösungsvorschläge, falls vorhanden
Das Problem mit einem Alert abfangen.

## Verantwortlicher als funktionaler Reviewer
- [ ] @CorvinFassbender

**Comment by NimsaJ150** [comment]
Sollte durch #107 eigentlich behoben worden sein. Bei mir funktioniert es auch. Gerne aber nochmal prüfen @Sofie273 @twonkos

**Comment by Sofie273** [comment]
Bereits durch 107 gelöst
