### ISSUE TITLE
Gleiche Metrik Namen

### ISSUE THREAD

**Issue by NimsaJ150** [Praxisprojekt2021/praxisprojekt#48]
## Bereich 

* Backend
   - Database-Handler

## Beschreibung

Es sollte verhindert werden eine Metrik existierende Metrik anzulegen. 

## Lösungsvorschläge, falls vorhanden

Bitte über eine Neo4j Funktion lösen und nicht via alle Metriken holen und vergleichen

## Verantwortlicher als funktionaler Reviewer
- [ ] @Timo-Buecher

**Comment by jonathan112358** [comment]
Verstehe das Issue ehrlich gesagt nicht ganz. Meinem Verständnis nach soll einfach keiner Metriken hinzufügen, bis auf das Initialisieren der DB im Falle eines Neustarts. Wieso sollte man dann eine Funktion bauen?

**Comment by Timo-Buecher** [comment]
Ich hätte gerne auf dem Name Feld einen unique identifier, einfach um zu verhindern, dass es technisch überhaupt möglich ist Metriken mit dem gleichen Namen zu erstellen.

**Comment by Sofie273** [comment]
Wenn man einen "unique identifier" auf name legt verhindert das leider noch nicht das doppelte erstellen einer Metrik

**Comment by Sofie273** [comment]
Ich schau mal nach anderen Lösungen

**Comment by Sofie273** [comment]
Ich habe eine Lösung gefunden @Timo-Buecher 
Dafür müsste man eine constraint in der neo4j Datenbank kreieren, also beim init der Application folgende Zeile ausführen: 

Create CONSTRAINT ON (n:Metric) ASSERT n.name IS UNIQUE
