### ISSUE TITLE
TODO: Score und Anzahl Komponenten dynamisch einfügen

### ISSUE THREAD

**Issue by AaronDesler** [Praxisprojekt2021/praxisprojekt#57]
## Bereich 
* Backend
   - Logik

## Beschreibung
TODO aus get_process_list() in core.py
"TODO: score und anzahl Komponenten dynamisch einfügen"

## Testen 
Neuer Task in Trello im nächsten Sprint?

## Verantwortlicher als funktionaler Reviewer
@NimsaJ150

**Comment by NimsaJ150** [comment]
@AaronDesler @Sofie273 fällt das nicht unter eure US 210 (Feature: Finalisieren der core-Funktionen)?

**Comment by AaronDesler** [comment]
@NimsaJ150 okay dann muss ich mal gucken wer das geschrieben hat

**Comment by NimsaJ150** [comment]
Ich habe das als Erinnerung an euch in den Code geschrieben ;)

**Comment by NimsaJ150** [comment]
Ihm Rahmen der Fertigstellung von 212 und dem Fertigstellen von core umgesetzt.
