### ISSUE TITLE
Neu Laden nach Prozess löschen

### ISSUE THREAD

**Issue by NimsaJ150** [Praxisprojekt2021/praxisprojekt#62]
## Bereich 

* Frontend

## Beschreibung

Aktuell wird nach dem Drücken des Löschen Buttons die Seite nicht neu geladen/eine Änderung angezeigt (oder es braucht sehr lange zum Laden)

## Lösungsvorschläge, falls vorhanden

Statt (oder während) neu Laden der Seite, wäre es vermutlich sinnvoll. die Tabellenzeile einfach auszublenden.

## Testen 

Es wird eine erkennbare Reaktion auf das Drücken des Löschen buttons angezeigt

## Verantwortlicher als funktionaler Reviewer
- [ ] @tomhinzmann

**Comment by Jan-Tiedemann** [comment]
@NimsaJ150 
Es geht hier um das Löschen von Komponenten auf der Prozessseite oder ? Weil auf der Startseite finde ich das Löschen gut umgesetzt.

**Comment by Jan-Tiedemann** [comment]
@NimsaJ150 

Also ich hab jetzt wie bei der Startseite den Alert beim deleteCallback reingehauen. Es kommt also nun ein Alert ob der delete geklappt hat oder nicht und dann werden die Komponenten neu geladen . Das ganze ist aber immer noch sehr delayed. Aber meiner Meinung nach würde es nun aber keinen Unterschied machen die Tabellenzeile zu löschen, da man das ja auch abhängig von der Response machen müsste und dann wäre es durch die Ladezeit genau so delayed.

Passt das dir so ?
