### ISSUE TITLE
Neo4j Ladezeit

### ISSUE THREAD

**Issue by Timo-Buecher** [Praxisprojekt2021/praxisprojekt#63]
## Bereich
* Backend
   - Database-Handler
* Database

## Beschreibung
Es kommt so sehr hohen Ladezeiten der Inhalte aus der Datenbank, wir müssen hierfür eine Lösung finden da dies die User Experience stark beeinträchtigt. Wir müssen zunächst den Grund für die lange Ladezeit finden. 

Mögliche Ursachen:
- Konfiguration der Neo4J Datenbank in der Cloud (ggf. müssen die beiden VMs ins gleiche virtuelle Netzwerk, damit die Latenz reduziert wird)
- Unsere Implementierung von Neomodel (auch wenn wir uns an die Doku gehalten haben)
- Neomodel selber
- weitere gerne ergänzen

## Lösungsvorschläge, falls vorhanden
Ggf. wenn möglich Batch Operations nutzen
Ggf. testen ob plain cypher queries schneller sind

Zum Ausgeben der ausgeführten Queries:
logging.basicConfig(level=logging.DEBUG)
NEOMODEL_CYPHER_DEBUG = 1

Zum messen der Zeiten evtl. sowas nutzen (Quelle: Stackoverflow):
    ----------------------
Given a function you'd like to time,

test.py:

```
def foo(): 
    # print "hello"   
    return "hello"
```
the easiest way to use timeit is to call it from the command line:

`% python -mtimeit -s'import test' 'test.foo()'`
1000000 loops, best of 3: 0.254 usec per loop
Do not try to use time.time or time.clock (naively) to compare the speed of functions. They can give misleading results.

PS. Do not put print statements in a function you wish to time; otherwise the time measured will depend on the speed of the terminal.
    ----------------------

## Testen 
Die Ladezeiten müssen massiv reduziert sein, sowohl für Komponenten als auch Prozesse und insbesondere die Prozessliste.

## Verantwortlicher als funktionaler Reviewer
- @Timo-Buecher & @Antonio1730 

### Abhängigkeiten
keine

**Comment by Timo-Buecher** [comment]
Finding 1:

Abfragen auf eine Locale DB sind deutlich schneller, d.h. die Latenz spielt auch bei unserem Problem eine Rolle. Wir sollten die Zeiten der DB in Google Cloud messen wenn diese vom Webserver in der Google Cloud aufgerufen wird. (nicht Webserver lokal laufen lassen und die DB aus der Cloud anfragen --> diese Zahlen bringen uns nichts) Wenn die Messwerte deutlich von den Lokalen (lokaler Webserver und lokale Neo4j DB) abweichen, müssen wir schauen wie wir die beiden Server ins gleiche Netzwerk bekommen. 

Hier bitte mit  @sascha7777 und @luke-fs sprechen und hier immer Updates geben.

**Comment by Timo-Buecher** [comment]
Finding 2:

Es gibt anscheinend eine Art "Handshake" o.Ä. der relativ lange dauert. Die erste Datenbank Operation in einer Funktion dauert meist um die 2 Sekunden (getestet im Component Handler). Die gleiche Abfrage danach braucht nur einen Bruchteil der Zeit.
`
get_component_node: 2.013904333114624
get_component_node: 0.0029592514038085938
`
Für mich scheint es so, als ob bei jeder Funktion eine Verbindung zur DB aufgebaut wird (das dauert dann einige Zeit), innerhalb der Funktion wird diese Connection dann genutzt und es sehr schnell. Mit dem Ende der Funktion wird diese Connection wieder beendet. Praktisch wäre es wenn wir es schaffen diese Connection dauerhaft offen zu lassen, also z.B. wie bei JDBC das Connection Objekt zu übergeben oder die Verbindung irgendwo global zu öffnen. Ich hab dazu nichts in der Neomodel Doku nichts gefunden, zur Not müssen wir den Neomodel Code mal tiefer analyiseren. Da unterstüze ich auch gerne.

Es könnte allerdings auch einen anderen Grund haben, das sind nur meine erste Vermutung.

Das bitte im Austausch mit mir bearbeiten.

**Comment by sascha7777** [comment]
@luke-fs und @Timo-Buecher 
Die Compute Engine, auf der Neo4j läuft, ist derzeit auf "US-central" konfiguriert, das könnte meiner Meinung nach eine Ursache sein.
![image](https://user-images.githubusercontent.com/43936809/114305219-68b0de80-9ad7-11eb-86ee-672941ead6fe.png)

**Comment by luke-fs** [comment]
Die ist auf US konfiguriert, weil es nur dann unter dem Free Tier läuft. Europäische Zones sind kostenpflichtig. Es gibt 3 US Zones, die unter den Free Tier fallen.
Ich nutze aber sehr viele Google Cloud Produkte (wovon viele auch auf US laufen) und ich bin mir ziemlich sicher, dass die Latenz nur sehr sehr gering darunter leidet. Ich hatte noch nie der Erfahrung gemacht, dass die Latenz von US Servern merkbar schlechter ist. Falls ihr alles andere ausgeschlossen habt, könnte man mal eine neue Test-Instanz von einer deutschen Zone erstellen und testen, ob die Latenz hier besser ist. Die Zone einer bestehenden VM ändern, kann man jedoch leider nicht.

**Comment by Timo-Buecher** [comment]
> Die ist auf US konfiguriert, weil es nur dann unter dem Free Tier läuft. Europäische Zones sind kostenpflichtig. Es gibt 3 US Zones, die unter den Free Tier fallen.
> Ich nutze aber sehr viele Google Cloud Produkte (wovon viele auch auf US laufen) und ich bin mir ziemlich sicher, dass die Latenz nur sehr sehr gering darunter leidet. Ich hatte noch nie der Erfahrung gemacht, dass die Latenz von US Servern merkbar schlechter ist. Falls ihr alles andere ausgeschlossen habt, könnte man mal eine neue Test-Instanz von einer deutschen Zone erstellen und testen, ob die Latenz hier besser ist. Die Zone einer bestehenden VM ändern, kann man jedoch leider nicht.

Ich glaube auch weniger das es an der Region liegt, sondern vielmehr das die beides VMs in unterschiedlichen Netzwerken sind und dann durch X Firewalls etc. durchmüssen. Weil local sind die exakt gleichen Abfragen teilweise 10x schneller. Aber ich würde auch erstmal das zweite Finding von mir prüfen. außer ihr findet sofort die Netzwerkeinstellungen, wenn das bei Google Cloud geht. Bei AWS kann man verschiedene Server einfach ins gleiche virtuelle Netzwerk packen und dann ist das wie ein lokales Netzwerk auf dem PC

**Comment by twonkos** [comment]
> Ich glaube auch weniger das es an der Region liegt, sondern vielmehr das die beides VMs in unterschiedlichen Netzwerken sind und dann durch X Firewalls etc. durchmüssen. Weil local sind die exakt gleichen Abfragen teilweise 10x schneller. Aber ich würde auch erstmal das zweite Finding von mir prüfen. außer ihr findet sofort die Netzwerkeinstellungen, wenn das bei Google Cloud geht. Bei AWS kann man verschiedene Server einfach ins gleiche virtuelle Netzwerk packen und dann ist das wie ein lokales Netzwerk auf dem PC

An dem Finding 2 ist auf jeden Fall etwas dran. Wenn man eine Komponente zum bearbeiten öffnet beträgt die Ladezeit ca. 3 Sek, wenn mehr Komponenten geladen werden müssen 7+ Sekunden
