### ISSUE TITLE
Beschreibungsfeld mit Leerzeichen gefüllt

### ISSUE THREAD

**Issue by NimsaJ150** [Praxisprojekt2021/praxisprojekt#65]
## Bereich 

* Frontend

## Beschreibung

Es wird im Beschreibungsfeld der Komponenten Leerzeichen vorgeladen.

![image](https://user-images.githubusercontent.com/44087726/114398858-90b84480-9ba0-11eb-9c10-b9223cef6b0b.png)

## Reproduktion

- eine neue Komponente anlegen
- notfalls mehrfach neuladen

## Lösungsvorschläge

- bei der Prozessview hat es geholfen, den schließenden Textarea Tag direkt an den öffnenden Tag zu packen -> bei Komponenten auf die schnelle nicht, kann aber gerne nochmal probiert werden

## Testen 

- keine Leerzeichen mehr im Feld

## Verantwortlicher als funktionaler Reviewer
- [ ] @tomhinzmann

**Comment by twonkos** [comment]
Der Lösungsvorschlag hat geklappt

Hab ich im 246 Zwischenstand noch mitgenommen
