### ISSUE TITLE
Deutsche Beschreibungen in Einzel-Views

### ISSUE THREAD

**Issue by Sofie273** [Praxisprojekt2021/praxisprojekt#75]
## Bereich 
* Frontend

## Beschreibung
Bezeichnungen im Processview & ComponentView sind hardgecoded auf deutsch und werden nicht über json eingelesen
![image](https://user-images.githubusercontent.com/44003828/114761458-c73cbd80-9d60-11eb-9d68-095c4bb56e1d.png)
![image](https://user-images.githubusercontent.com/44003828/114761032-4f6e9300-9d60-11eb-9740-5de00aac62e9.png)
![image](https://user-images.githubusercontent.com/44003828/114761166-7036e880-9d60-11eb-807a-ff0c9b17a19d.png)

## Reproduktion
Öffnen der Prozess View

## Lösungsvorschläge
Aufnehmen der Parameter in en.json, entsprechende Struktur im JS Handler schaffen (init funktion)

## Testen 
Im Frontend schauen obs Englisch ist

## Verantwortlicher als funktionaler Reviewer
- [ ] @tomhinzmann

**Comment by N3R1K** [comment]
Habe es in Branch:
I75_Deutsche_Beschreibungen_in_Einzel-Views
gepushed. ✅
