### ISSUE TITLE
mapping metrics defintion helper text

### ISSUE THREAD

**Issue by Sofie273** [Praxisprojekt2021/praxisprojekt#77]
## Bereich 
* Frontend

## Beschreibung
Beim EInfügen der desctiptions (die wir teilweise für component & process unterscheiden müssen), ist uns aufgefallen, dass der helper-text in der mapping definition json uneinheitlich entweder die descriptions oder die examples benutzt -> es sollte geschaut werden, wo der helper text verwendet wird und auf die entsprechende description zugegriffen werden.

## Reproduktion
Schauen ins JSON

## Lösungsvorschläge
Nach abhängigkeiten im javascript schauen und die zugriffe mit fallunterscheidung auf descriptions anpassen

## Testen 
Überprüfen, ob die Texte im Frontend korrekt angezeigt werden + helper text im json entfernt

## Verantwortlicher als funktionaler Reviewer
- [ ] @tomhinzmann /@Sofie273 

### Anmerkungen
Bitte auf merge Branch  287_infotexte_metriken warten, da hier die texte angepasst wurden

**Comment by AaronDesler** [comment]
helper_text wird außerhalb von mapping_metrics_definition.json nicht gefunden
Alle helper_text gelöscht.
Im Frontend werden keine Infotexte angezeigt, die entsprechenden Buttons sind nur Images, daher kein Test der korrekten Anzeige im Frontend
