### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by NimsaJ150** [Praxisprojekt2021/praxisprojekt#79]
## Bereich 

* Frontend

## Beschreibung

Aufräumen der Callbacks, dh. alle POST/GET Funktionen rufen einen einheitlichen Callback auf. Dabei auch neu Modularisieren aller POST und GET Requests

Am Besten gemeinsam mit @Timo-Buecher @NimsaJ150 und @tomhinzmann brainstormen.

## Verantwortlicher als funktionaler Reviewer
- [ ] @tomhinzmann  

### Anmerkungen

Initiale Absprache bitte mit @tomhinzmann @NimsaJ150 @Timo-Buecher

**Comment by lucabloe** [comment]
Fix befindet sich auf Branch i79_callback, Pull Request wurde erstellt. @NimsaJ150 @tomhinzmann
