### ISSUE TITLE
Inconsistent comments

### ISSUE THREAD

**Issue by AaronDesler** [Praxisprojekt2021/praxisprojekt#80]
## Bereich 
* Backend
   - Logik
   - Database-Handler

## Beschreibung
Commenting style in database/handler/component_handler.py incompliant with standard

## Lösungsvorschläge
Fix

## Verantwortlicher als funktionaler Reviewer
@NimsaJ150 ?

**Comment by NimsaJ150** [comment]
@AaronDesler inwiefern ist es incompliant? Also was stimmt bspw. nicht?
