### ISSUE TITLE
WIP: Process Deletion Reload

### ISSUE THREAD

**Issue by jonathan112358** [Praxisprojekt2021/praxisprojekt#85]
## Bereich 
* Frontend

## Beschreibung
Aktuell wird nach dem Löschen eines Prozesses auf der Startseite alles neu geladen. Dies bedeutet, dass alle Prozesse neu geladen werden.

## Reproduktion
Prozess löschen

## Lösungsvorschläge
Löschvorgang wird vom Frontend an die Datenbank geschickt und das Feld wird nur im Frontend entfernt, ohne einen Reload anzustoßen.

## Testen 
Prozess löschen

## Verantwortlicher als funktionaler Reviewer
- [ ] @NimsaJ150

**Comment by NimsaJ150** [comment]
@jonathan112358 @Timo-Buecher genau den Issue hatten wir schon mal und haben uns dagegen entschieden, das so umzusetzen. -> Fall, dass Löschen fehlschlägt. Mit den neuen Ladezeiten sollte es auch kein Problem mehr sein. Wenn sollte ohnehin das Loading popup auftauchen. Gerne eure Meinung dazu :)

**Comment by Timo-Buecher** [comment]
Hab ich auch so im Kopf, sollten wir aber trotzdem mal drüber sprechen ob es in dem Fall nicht besser wäre die Daten nicht jedes mal abzufragen. Bin da _open for discussion_

**Comment by jonathan112358** [comment]
Hm, ja mit der neuen Version ist es natürlich unproblematischer, aber generell würde ich halt schon sagen, dass man eigentlich nur auf den Success Handler gucken sollte. Habe jetzt aber kein fundamentales Problem damit es so zu lassen. Wie hoch wäre denn der Änderungsaufwand im Frontend?

**Comment by NimsaJ150** [comment]
@tomhinzmann
