### ISSUE TITLE
WIP: Logo vereinheitlichen

### ISSUE THREAD

**Issue by lucabloe** [Praxisprojekt2021/praxisprojekt#87]
## Bereich 

* Frontend

## Beschreibung

Auf der Startseite ist wird das Riskify-Logo als Text eingefügt und auf den Komponenten- und Prozessseiten als Bild.

Logo auf der Prozessseite:
![image](https://user-images.githubusercontent.com/79468744/115144477-32caa780-a04d-11eb-95dd-185e6922b1af.png)

Logo auf der Startseite:
![image](https://user-images.githubusercontent.com/79468744/115144497-4e35b280-a04d-11eb-85e1-63047e74886f.png)

## Lösungsvorschläge

Zuerst sollte entschieden werden, ob das Logo als Bild oder Text eingefügt werden soll. Falls es als Text eingefügt werden soll, muss außerdem im CSS noch die Farbe des Textes auf das riskify-grün geändert werden.
Dann sollte es überall einheitlich umgesetzt werden.

## Testen 

Riskify-Logo ist auf allen Seiten einheitlich als Bild oder Text eingefügt.

## Verantwortlicher als funktionaler Reviewer
- [ ] tba

**Comment by NimsaJ150** [comment]
@twonkos Hey, kümmerst du dich hier auch schon mit drum in deinem Design Task? :)

**Comment by twonkos** [comment]
@NimsaJ150 @lucabloe Yes, kommt mit der vereinheitlichung des Designs

**Comment by jonathan112358** [comment]
Persönlicher Geschmack @twonkos: Finde das Bild mit dem Grün um einiges schöner.
