### ISSUE TITLE
Dauerladescreen bei saveComponent mit fehlerhaften Eingaben

### ISSUE THREAD

**Issue by NimsaJ150** [Praxisprojekt2021/praxisprojekt#95]
## Bereich 

* Frontend

## Beschreibung

Wenn eine Komponente mit fehlerhaften Eingaben (oder fehlenden) versucht wird zu speichern, kommt nach der Fehlermeldung der Ladescreen, der nicht mehr weg geht.

## Lösungsvorschläge

Bitte testen, ob das Problem tatsächlich besteht, möglicherweise auch bei Prozessen? Und wenn ja, entsprechenden Aufruf von hideLoadingScreen() einpflegen.

## Testen 

Man kann nach den fehlerhaften Versuch eine Komponente zu speichern, diese weiter bearbeiten.

## Verantwortlicher als funktionaler Reviewer
- [ ] @NimsaJ150

**Comment by twonkos** [comment]
Sollte behoben sein, siehe Kommentar
https://github.com/Praxisprojekt2021/praxisprojekt/pull/100#issuecomment-824484906
